language: java
before_script:
  - curl -O https://raw.githubusercontent.com/Ahmad-Ayyoub/guides-common/travis/ci-script.sh
script: 
  - cd finish
  - mvn clean install
  - build=$( grep "Open Liberty" target/liberty/wlp/usr/servers/defaultServer/logs/console.log | cut -d' ' -f5 | cut -d')' -f1 ); release=$( echo "$build" | cut -d'/' -f1); number=$( echo "$build" | cut -d'/' -f2); echo  "Open Liberty release $release"; echo  "Open Liberty build number $number";
